Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Fundamentals.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Fundamentals.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
	}
}

Pages/Movies/ClientMovies.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NET_Core_Fundamentals.Pages.Movies
{
    public class ClientMoviesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Movies/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fundamentals.Core;
using Fundamentals.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NET_Core_Fundamentals.Pages.Movies
{
    public class DeleteModel : PageModel
    {
		private readonly IMovieData movieData;
		public Movie Movie { get; set; }

		public DeleteModel(IMovieData movieData)
		{
			this.movieData = movieData;
		}
		public IActionResult OnGet(int movieId)
		{
			Movie = movieData.GetById(movieId);
			if (Movie == null)
			{
				return RedirectToPage("./NotFound");
			}
			return Page();
		}

		public IActionResult OnPost(int movieId)
		{
			var movie = movieData.Delete(movieId);
			movieData.Commit();

			if (movie == null)
			{
				return RedirectToPage("./NotFound");
			}
			TempData["Message"] = $"{movie.Title} deleted";
			return RedirectToPage("./List");
		}
	}
}

Pages/Movies/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fundamentals.Core;
using Fundamentals.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NET_Core_Fundamentals.Pages.Movies
{
    public class DetailModel : PageModel
    {
		private readonly IMovieData movieData;
		[TempData]
		public string Message { get; set; }

		public DetailModel(IMovieData movieData)
		{
			this.movieData = movieData;
		}
		public Movie Movie { get; set; }
		public IActionResult OnGet(int movieId)
		{
			Movie = movieData.GetById(movieId);
			if (Movie == null)
			{
				return RedirectToPage("./NotFound");
			}
			return Page();
		}
	}
}

Pages/Movies/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fundamentals.Core;
using Fundamentals.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP.NET_Core_Fundamentals.Pages.Movies
{
    public class EditModel : PageModel
    {
		private readonly IMovieData movieData;
		private readonly IHtmlHelper htmlHelper;
		[BindProperty]
		public Movie Movie { get; set; }
		public IEnumerable<SelectListItem> Ratings { get; set; }

		public EditModel(IMovieData movieData, IHtmlHelper htmlHelper)
		{
			this.movieData = movieData;
			this.htmlHelper = htmlHelper;
		}
		public IActionResult OnGet(int? movieId)
		{
			Ratings = htmlHelper.GetEnumSelectList<Rating>();
			if (movieId.HasValue)
			{
				Movie = movieData.GetById(movieId.Value);
			}
			else
			{
				Movie = new Movie();
			}
			if (Movie == null)
			{
				return RedirectToPage("./NotFound");
			}
			return Page();
		}

		public IActionResult OnPost()
		{
			if (!ModelState.IsValid)
			{
				Ratings = htmlHelper.GetEnumSelectList<Rating>();
				return Page();
			}
			if (Movie.MovieId > 0)
			{
				movieData.Update(Movie);
			}
			else
			{
				movieData.Add(Movie);
			}
			movieData.Commit();
			TempData["Message"] = "Movie saved: " + Movie.Title;
			return RedirectToPage("./Detail", new { movieId = Movie.MovieId });
		}
	}
}

Pages/Movies/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fundamentals.Core;
using Fundamentals.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace ASP.NET_Core_Fundamentals.Pages.Movies
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IMovieData movieData;
		private readonly ILogger<ListModel> logger;

		public string Message { get; set; }
        public IEnumerable<Movie> Movies { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }


        public ListModel(IConfiguration config, IMovieData movieData, ILogger<ListModel> logger)
        {
            this.config = config;
            this.movieData = movieData;
			this.logger = logger;
		}

        public void OnGet(string searchTerm)
        {

            //Message = config["Message"];
            //Movies = movieData.GetAll();
            logger.LogInformation("Executing ListModel");
            Movies = movieData.GetMovieByName(searchTerm);
        }
    }
}

Pages/Movies/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NET_Core_Fundamentals.Pages.Movies
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Fundamentals.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

ViewComponents/MovieCountViewComponent.cs
using Fundamentals.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Fundamentals.ViewComponents
{
	public class MovieCountViewComponent :ViewComponent
	{
		private readonly IMovieData movieData;

		public MovieCountViewComponent(IMovieData movieData)
		{
			this.movieData = movieData;
		}

		public IViewComponentResult Invoke()
		{
			var count = movieData.GetCountOfMovies();
			return View(count);
		}
	}
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Movies/ClientMovies.cshtml
@page
@model ASP.NET_Core_Fundamentals.Pages.Movies.ClientMoviesModel
@{
	ViewData["Title"] = "ClientMovies";
}

<h2>Client Movies</h2>

<table class="table" id="movies">
	
</table>

@section Scripts{

	<script src="\node_modules\datatables.net\js\jquery.dataTables.js"></script>
	<link href="\node_modules\datatables.net-bs4\css\dataTables.bootstrap4.css" rel="stylesheet" />
	<script src="\node_modules\datatables.net-bs4\js\dataTables.bootstrap4.js"></script>

	<script>

		$(function () {
			var rating = ["None", "One", "Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten"]
			$.ajax("/api/movies/",
				{ method: "get" })
				.then(function (response) {
					$("#movies").dataTable({
						data: response,
						
						columns: [
							{ "data": "title" },
							{ "data": "director" },
							{ "data": "producer" },
							{ 
								"data": "rating", "render": function (data) {
									return rating[data];
								}
							}

						]
					});
				});
		});

	</script>
}

Pages/Movies/Delete.cshtml
@page  "{movieId}"
@model ASP.NET_Core_Fundamentals.Pages.Movies.DeleteModel
@{
	ViewData["Title"] = "Delete";
}


<h2>Delete!</h2>
<div class="alert alert-danger">
	Are you sure you want to delete @Model.Movie.Title?
</div>
<form method="post">
	<button type="submit" class="btn btn-danger">Yes!</button>
	<a asp-page="List" class="btn btn-danger">Cancel</a>
</form>

Pages/Movies/Detail.cshtml
@page "{movieId:int}"
@model ASP.NET_Core_Fundamentals.Pages.Movies.DetailModel


<h2>@Model.Movie.Title</h2>
@if (Model.Message != null)
{
	<div class="alert alert-info">@Model.Message</div>
}
<table class="table">
	<tr>
		<td>Title:</td>
		<td>EpisodeId</td>
		<td>OpeningCrawl</td>
		<td>Director</td>
		<td>Producer</td>
		<td>ReleaseDate</td>
		<td>Characters</td>
		<td>Planets</td>
		<td>Species</td>
		<td>Vehicles</td>
		<td>Starships</td>
		<td>Rating</td>
	</tr>

	<tr>
		<td>@Model.Movie.Title</td>
		<td>@Model.Movie.EpisodeId</td>
		<td>@Model.Movie.OpeningCrawl</td>
		<td>@Model.Movie.Director</td>
		<td>@Model.Movie.Producer</td>
		<td>@Model.Movie.ReleaseDate</td>
		<td>@Model.Movie.Characters</td>
		<td>@Model.Movie.Planets</td>
		<td>@Model.Movie.Species</td>
		<td>@Model.Movie.Vehicles</td>
		<td>@Model.Movie.Starships</td>
		<td>@Model.Movie.Rating</td>
	</tr>

</table>

<a asp-page="./List" class="btn btn-light">All Movies</a>

Pages/Movies/Edit.cshtml
@page "{movieId:int?}"
@model ASP.NET_Core_Fundamentals.Pages.Movies.EditModel
@{
	ViewData["Title"] = "Edit";
}

<h2>Editing @Model.Movie.Title</h2>

<form method="post">

	<input type="hidden" asp-for="Movie.MovieId" />
	<div class="form-group">
		<label asp-for="Movie.Title"></label>
		<input asp-for="Movie.Title" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Title"></span>
	</div>

	<div class="form-group">
		<label asp-for="Movie.EpisodeId"></label>
		<input asp-for="Movie.EpisodeId" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.EpisodeId"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.OpeningCrawl"></label>
		<input asp-for="Movie.OpeningCrawl" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.OpeningCrawl"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Director"></label>
		<input asp-for="Movie.Director" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Director"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Producer"></label>
		<input asp-for="Movie.Producer" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Producer"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.ReleaseDate"></label>
		<input asp-for="Movie.ReleaseDate" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.ReleaseDate"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Characters"></label>
		<input asp-for="Movie.Characters" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Characters"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Planets"></label>
		<input asp-for="Movie.Planets" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Planets"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Species"></label>
		<input asp-for="Movie.Species" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Species"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Vehicles"></label>
		<input asp-for="Movie.Vehicles" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Vehicles"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Starships"></label>
		<input asp-for="Movie.Starships" class="form-control" />
		<span class="text-danger" asp-validation-for="Movie.Starships"></span>

	</div>
	<div class="form-group">
		<label asp-for="Movie.Rating"></label>
		<select class="form-control" asp-for="Movie.Rating" asp-items="Model.Ratings">
		</select>
		<span class="text-danger" asp-validation-for="Movie.Rating"></span>
	</div>

	<button type="submit" class="btn btn-light">Save</button>
</form>

@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

Pages/Movies/List.cshtml
@page
@model ASP.NET_Core_Fundamentals.Pages.Movies.ListModel
@{
	ViewData["Title"] = "Movies";

}

<script src="https://kit.fontawesome.com/88fd76f067.js" crossorigin="anonymous"></script>
<h1>List of Movies</h1>

<form method="get">
	<div class="form-group">
		<div class="input-group">
			<input type="search" class="form-control" asp-for="SearchTerm" />
			<span class="input-group-btn">
				<button class="btn btn-default">
					<i class="fas fa-search"></i>
				</button>
			</span>
		</div>
	</div>
</form>
<a class="btn btn-light" asp-page="./Edit">Add New</a>

<table class="table">
	<tr>
		<td>Title:</td>
		<td>EpisodeId</td>
		<td>OpeningCrawl</td>
		<td>Director</td>
		<td>Producer</td>
		<td>ReleaseDate</td>
		<td>Rating</td>
	</tr>

	@foreach (var movie in Model.Movies)
	{

		<tr>
			<td>@movie.Title</td>
			<td>@movie.EpisodeId</td>
			<td>@movie.OpeningCrawl</td>
			<td>@movie.Director</td>
			<td>@movie.Producer</td>
			<td>@movie.ReleaseDate</td>
			<td>@movie.Rating</td>

			<td>
				<a asp-page="./Detail" asp-route-movieId="@movie.MovieId"><i class="fas fa-info-circle"></i></a>
			<td>
				<a asp-page="./Edit" asp-route-movieId="@movie.MovieId"><i class="fas fa-edit"></i></a>
			</td>
			<td>
				<a asp-page="./Delete" asp-route-movieId="@movie.MovieId"><i class="fas fa-trash-alt"></i> </a>
			</td>

		</tr>
	}
</table>

Pages/Movies/NotFound.cshtml
@page
@model ASP.NET_Core_Fundamentals.Pages.Movies.NotFoundModel
@{
	ViewData["Title"] = "NotFound";
}

<h2>You movie was not found!</h2>
<a asp-page="./List" class="btn btn-light">See all movies</a>

Pages/Movies/_Summary.cshtml
@using Fundamentals.Core
@model Movie

<div class="modal-content">
	<div class="modal-header" style="background-color:cornflowerblue">
		<h3>@Model.Title</h3>
	</div>
	@*<div class="modal-body"  style="background-color:darkgray"></div>*@
	<span>Director: @Model.Director</span>
	<span>EpisodeId: @Model.EpisodeId</span>
	<span>OpeningCrawl: @Model.OpeningCrawl</span>
	<span>ReleaseDate: @Model.ReleaseDate</span>
	<span>Producer: @Model.Producer</span>
	<span>Rating: @Model.Rating</span>


	<div class="modal-footer" style="background-color:darkgray">
		<a asp-page="./Detail" asp-route-movieId="@Model.MovieId"><i class="fas fa-info-circle"></i></a>
		<a asp-page="./Edit" asp-route-movieId="@Model.MovieId"><i class="fas fa-edit"></i></a>
		<a asp-page="./Delete" asp-route-movieId="@Model.MovieId"><i class="fas fa-trash-alt"></i> </a>
	</div>

</div>

Pages/Shared/Components/MovieCount/Default.cshtml
@model int

<div class="well">
	There are @Model movies here. <a asp-page="/Movies/List">See them all</a>
</div> 

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET_Core_Fundamentals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ASP.NET_Core_Fundamentals</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-page="/Movies/List">Movies</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-page="/Movies/ClientMovies">Client Movies</a>
						</li>
					</ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

	<footer class="border-top footer text-muted">
		@RenderSection("footer", required: false)
		<div class="container">
		<vc:movie-count></vc:movie-count>
		<img src="~/starwars.jpg" />
			&copy; 2021 - Nickolas - <a asp-area="" asp-page="/Privacy">Privacy</a>
		</div>
	</footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>